# This is a sample build configuration for Python.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
image: themattrix/tox

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - python3.6 --version
          - pip3.6 --version
          - tox --version
          - pip2.7 install -U numpy cython pycifrw ddt rowan tqdm
          - pip3.4 install -U numpy cython pycifrw ddt rowan tqdm
          - pip3.5 install -U numpy cython pycifrw ddt rowan tqdm
          - pip3.6 install -U numpy cython pycifrw ddt rowan tqdm
          - wget https://bitbucket.org/glotzer/gsd/get/master.tar.gz -O gsd.tar.gz
          - tar -xvzf gsd.tar.gz
          - cd glotzer-gsd-*
          - python2.7 setup.py install
          - python3.4 setup.py install
          - python3.5 setup.py install
          - python3.6 setup.py install
          - cd ..
          - wget https://bitbucket.org/glotzer/libgetar/get/master.tar.gz -O libgetar.tar.gz
          - tar -xvzf libgetar.tar.gz
          - cd glotzer-libgetar-*
          - python2.7 setup.py install
          - python3.4 setup.py install
          - python3.5 setup.py install
          - python3.6 setup.py install
          - cd ..
          - python3.6 -c "import numpy; print('numpy', numpy.__version__)"
          - python3.6 -c "import cython; print('cython', cython.__version__)"
          - python3.6 -c "import gsd; print('gsd', gsd.__version__)"
          - python3.6 -c "import gtar; print('gtar', gtar.__version__)"
          - python3.6 -c "import rowan; print('rowan', rowan.__version__)"
          - python3.6 -c "import pkg_resources; print('pycifrw', pkg_resources.require('pycifrw')[0].version)"
          - python2.7 setup.py build
          - python2.7 -m unittest discover tests/ -v
          - python3.4 setup.py build
          - python3.4 -m unittest discover tests/ -v
          - python3.5 setup.py build
          - python3.5 -m unittest discover tests/ -v
          - python3.6 setup.py build
          - python3.6 -m unittest discover tests/ -v
