# This is a sample build configuration for Python.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
image: python:3.5.1

pipelines:
  default:
    - step:
        image: python:3.5.1
        script: # Modify the commands below to build your repository.
          - pip install -U tox cython numpy
          - pip --version
          - tox --version
          - python setup.py build
          - python -m unittest discover tests/ -v
    - step:
        image: python:2.7.12
        script: # Modify the commands below to build your repository.
          - pip install -U tox cython numpy
          - pip --version
          - tox --version
          - python setup.py build
          - python -m unittest discover tests/ -v
#  branches:
#    master:
#      - step:
#          image: python:3.4.5
#          script: # Modify the commands below to build your repository.
#            - pip install -U tox cython numpy
#            - pip --version
#            - tox --version
#            - python setup.py build
#            - python -m unittest discover tests/ -v
#      - step:
#          image: python:3.3.5
#          script: # Modify the commands below to build your repository.
#            - pip install -U tox cython numpy
#            - pip --version
#            - tox --version
#            - python setup.py build
#            - python -m unittest discover tests/ -v
#      - step:
#          image: python:2.7.12
#          script: # Modify the commands below to build your repository.
#            - pip install -U tox cython numpy
#            - pip --version
#            - tox --version
#            - python setup.py build
#            - python -m unittest discover tests/ -v
#    develop:
#      - step:
#          image: python:3.4.5
#          script: # Modify the commands below to build your repository.
#            - pip install -U tox cython numpy
#            - pip --version
#            - tox --version
#            - python setup.py build
#            - python -m unittest discover tests/ -v
#      - step:
#          image: python:3.3.5
#          script: # Modify the commands below to build your repository.
#            - pip install -U tox cython numpy
#            - pip --version
#            - tox --version
#            - python setup.py build
#            - python -m unittest discover tests/ -v
#      - step:
#          image: python:2.7.12
#          script: # Modify the commands below to build your repository.
#            - pip install -U tox cython numpy
#            - pip --version
#            - tox --version
#            - python setup.py build
#            - python -m unittest discover tests/ -v
