# This is a sample build configuration for Python.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
image: themattrix/tox

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - python3.6 --version
          - pip3.6 --version
          - tox --version
          - pip3.6 install -U numpy cython
          - python3.6 setup.py build
          - python3.6 -m unittest discover tests/ -v
          - tox
