# This is a sample build configuration for Python.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
image: themattrix/tox

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - pip install -U numpy cython
          - pip --version
          - tox --version
          - python setup.py build
          - python -m unittest discover tests/ -v
          - tox
