# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  style-check:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: style-check
          command: |
            pip install --user -U flake8==3.7.1
            python -m flake8 --show-source .


  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python --version
            pip --version
            pip install --user -r .circleci/requirements.txt
            python setup.py build

      - run:
          name: Run tests
          command: |
            python -m unittest discover tests/ -v
            python -m coverage run -m unittest discover tests/
            python -m coverage report

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5

  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6

  test-deploy-pypi:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: test-deploy-pypi
          command: |
            pip install --user -U -r .requirements-deploy.txt
            bash .test-deploy.bash

  deploy-pypi:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: deploy-pypi
          command: |
            pip install --user -U -r .requirements-deploy.txt
            bash .deploy.bash

workflows:
  version: 2
  style-check-and-tests:
    jobs:
      - style-check
      - test-3.5:
          requires:
            - style-check
      - test-3.6:
          requires:
            - style-check
      - test-3.7:
          requires:
            - style-check
      - test-deploy-pypi:
          filters:
            branches:
              only: /release\/.*/
          requires:
            - test-3.5
            - test-3.6
            - test-3.7
  deploy:
    jobs:
      - deploy-pypi:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
