# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  style-check:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: style-check
          command: |
            pip install --user -U flake8==3.7.9
            python -m flake8 --show-source .


  test-py38: &test-template
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python --version
            pip --version
            pip install --user -r requirements-dev.txt
            python setup.py build

      - run:
          name: Run tests
          command: |
            python -m coverage run -m unittest discover tests/ -v
            python -m coverage report

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test-py37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

  test-py36:
    <<: *test-template
    docker:
      - image: circleci/python:3.6

  test-py35:
    <<: *test-template
    docker:
      - image: circleci/python:3.5

  test-integration:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Prepare conda
          command: |
            conda init bash

      - run:
          name: Install compilers
          command: |
            conda activate base
            conda install -c conda-forge gcc_linux-64 gxx_linux-64 --yes --quiet

      - run:
          name: Install dependencies
          command: |
            conda activate base
            conda install -c conda-forge -c schrodinger fresnel hoomd matplotlib-base povray --yes --quiet
            python --version
            pip --version
            pip install --user -r requirements-dev.txt
            pip install --user plato-draw
            python setup.py build

      - run:
          name: Run tests
          command: |
            python -m coverage run -m unittest discover tests/ -v
            python -m coverage report

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test-deploy-pypi:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: test-deploy-pypi
          command: |
            bash .circleci/deploy.bash testpypi

  deploy-pypi:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: deploy-pypi
          command: |
            bash .circleci/deploy.bash pypi

workflows:
  version: 2
  style-check-and-tests:
    jobs:
      - style-check
      - test-py38:
          requires:
            - style-check
      - test-py37:
          requires:
            - style-check
      - test-py36:
          requires:
            - style-check
      - test-py35:
          requires:
            - style-check
      - test-integration:
          requires:
            - test-py38
            - test-py37
            - test-py36
            - test-py35
      - test-deploy-pypi:
          filters:
            branches:
              only: /release\/.*/
          requires:
            - test-py38
            - test-py37
            - test-py36
            - test-py35
            - test-integration
  deploy:
    jobs:
      - deploy-pypi:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
